server:
  port: ${SERVER_PORT:8080}

grpc:
  server:
    port: ${GRPC_PORT:50051}
    enabled: true

spring:
  application:
    name: payments-monolith

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

  jta:
    enabled: true
# DATASOURCES (variables env para facilitar docker)
datasources:
  inventory:
    url: ${SPRING_DATASOURCE_INVENTORY_URL:jdbc:mysql://127.0.0.1:3307/inventory?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${SPRING_DATASOURCE_INVENTORY_USERNAME:simis}
    password: ${SPRING_DATASOURCE_INVENTORY_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  payments:
    url: ${SPRING_DATASOURCE_PAYMENTS_URL:jdbc:mysql://127.0.0.1:3309/payments?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${SPRING_DATASOURCE_PAYMENTS_USERNAME:simis}
    password: ${SPRING_DATASOURCE_PAYMENTS_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  billing:
    url: ${SPRING_DATASOURCE_BILLING_URL:jdbc:mysql://127.0.0.1:3308/billing?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${SPRING_DATASOURCE_BILLING_USERNAME:simis}
    password: ${SPRING_DATASOURCE_BILLING_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  

services:
  inventoryBaseUrl: ${INVENTORY_BASE:http://localhost:8081}
  billingBaseUrl:   ${BILLING_BASE:http://localhost:8083}

logging:
  level:
    org.springframework: INFO
    com.taller5: DEBUG
    org.hibernate.SQL: DEBUG
