server:
  port: 8083
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3309/payments?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: simis
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

services:
  inventoryBaseUrl: http://localhost:8081
  billingBaseUrl:   http://localhost:8082
