server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3308/billing?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: simis
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
