server:
  port: 8083

spring:
  application:
    name: billing-service

aggregator:
  url: http://localhost:8090   # en contenedor usa host.docker.internal

feign:
  httpclient:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 5000
        loggerLevel: basic

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    com.taller5.billing.client: DEBUG
    feign: INFO
