server:
  port: 8083

spring:
  application:
    name: billing-service

  # Kafka Configuration
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  # ActiveMQ Artemis Configuration (WildFly integrated)
  artemis:
    mode: native
    broker-url: tcp://notification-mdb:61616?protocols=CORE
    user: admin
    password: admin123
    embedded:
      enabled: false  # CRÍTICO: Deshabilitar broker embebido
  jms:
    pub-sub-domain: false  # usar colas, no topics

aggregator:
  url: http://localhost:8090   # en contenedor usa host.docker.internal

feign:
  httpclient:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 5000
        loggerLevel: basic

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    com.taller5.billing.client: DEBUG
    feign: INFO
