server:
  port: 8081

spring:
  application:
    name: inventory-service

# URL del Aggregator/DAL (ajusta host/puerto si aplica)
aggregator:
  url: http://localhost:8090

feign:
  httpclient:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 5000
        loggerLevel: basic

management:
  endpoints:
    web:
      exposure:
        include: health,info,mappings

logging:
  level:
    com.taller5.inventory.dal: DEBUG   # logs de tu FeignClient
    feign: INFO                        # logs de Feign
